GET http://localhost:3000/api/filters/metadata/1717859010975 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxpYnJ1c251bWVyQGludGVyaWEucGwiLCJpYXQiOjE3MTc2OTU3MjgsImV4cCI6MTcxNzc4MjEyOH0.6EJ0fm7e2osvAzlIWx59t8b2EV-f_bkbX0lj8LQL4wY

###

GET http://localhost:3000/api/getimage/1717858716531 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxpYnJ1c251bWVyQGludGVyaWEucGwiLCJpYXQiOjE3MTc2OTU3MjgsImV4cCI6MTcxNzc4MjEyOH0.6EJ0fm7e2osvAzlIWx59t8b2EV-f_bkbX0lj8LQL4wY

###

PATCH http://localhost:3000/api/filters
Content-Type: 'application/json'

{
    "id": 1717776455318,
    "filter": "negate"
}

###

GET http://localhost:3000/api/getimage/1716896264046/filter/rotate HTTP/1.1

###