POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

user_album_jeden_test
------FormBoundary1234
###
GET http://localhost:3000/api/photos HTTP/1.1

###
GET http://localhost:3000/api/photos/1714413715887 HTTP/1.1

###

DELETE http://localhost:3000/api/photos/1714412177573 HTTP/1.1

###

PATCH http://localhost:3000/api/photos/1714412177573 HTTP/1.1