GET http://localhost:3000/api/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvbWluaWtvNzc3QGludGVyaWEucGwiLCJpYXQiOjE3MTc4MzY0ODIsImV4cCI6MTcxNzkyMjg4Mn0.76h_llRGTJuFSffGiCLFm7GMQ8aJc6IgeS74dCGhwVY

###

PATCH http://localhost:3000/api/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwucGwiLCJpYXQiOjE3MTcxODgyMDEsImV4cCI6MTcxNzI3NDYwMX0.QqMz86t9I7r1_GZjcP51y0PVoPgCnGFTGUlA49tFUlg
Content-Type: "application/json"

{
    "name": "john",
    "lastname": "snape"
}

###

POST http://localhost:3000/api/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvbWluaWtvNzc3QGludGVyaWEucGwiLCJpYXQiOjE3MTc4MzY0ODIsImV4cCI6MTcxNzkyMjg4Mn0.76h_llRGTJuFSffGiCLFm7GMQ8aJc6IgeS74dCGhwVY
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234

###

GET http://localhost:3000/api/profile/images HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvbWluaWtvNzc3QGludGVyaWEucGwiLCJpYXQiOjE3MTc4MzY0ODIsImV4cCI6MTcxNzkyMjg4Mn0.76h_llRGTJuFSffGiCLFm7GMQ8aJc6IgeS74dCGhwVY

###

GET http://localhost:3000/api/profile/picture HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxpYnJ1c251bWVyQGludGVyaWEucGwiLCJpYXQiOjE3MTc5MjI2MzMsImV4cCI6MTcxNzkyNjIzM30.zKlaNy6KzK77wA_gMIj4aVk_WRze_yhjYID4dePRn6c

