POST http://localhost:3000/api/user/register HTTP/1.1
Content-Type: "application/json"

{    
   "name": "house",
   "lastName": "lastName",
   "email":"dominiko777@interia.pl",
   "password":"password"
}

###
GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/user/login HTTP/1.1
Content-Type: "application/json"

{
   "email":"dominiko777@interia.pl",
   "password":"password"
}